### ISSUE TITLE
Disable local host check for health check

### ISSUE THREAD

**Issue by quorn23** [amir20/dozzle#2508]
**Is your feature request related to a problem? Please describe.**
Currently dozzle falls into an unhealthy state, when only remote hosts are configured.
`level=warning msg="Could not connect to local Docker Engine: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"`

**Describe the solution you'd like**
An environment variable that disables the local host usage, something like REMOTE_HOSTS_ONLY=true maybe?

**Describe alternatives you've considered**
Mounting back `/var/run/docker.sock`

**Comment by amir20** [comment]
Hmm,  I only look at the first client. 

https://github.com/amir20/dozzle/blob/eb94da7b92ea7ecb4ea6431c24c2a6abeaf9e45f/internal/web/healthcheck.go#L10-L24

> level=warning msg="Could not connect to local Docker Engine: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

That's only a warning. Does it actually fail?

**Comment by quorn23** [comment]
Restarted container and it does show up as unhealthy

```
level=info msg="Dozzle version v5.4.2"
level=warning msg="Could not connect to local Docker Engine: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
level=info msg="Creating client for HELL with tcp://hell:2375"
level=info msg="Creating client for Inferno with tcp://inferno:2375"
level=info msg="Connected to 2 Docker Engine(s)"
level=info msg="Accepting connections on :8080"
```

SS of unhealthy state
[https://img.amoklauf.ch/gOjE3/ROZulUtA75.jpg/raw](https://img.amoklauf.ch/gOjE3/ROZulUtA75.jpg/raw)

Compose snippet:

```
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    hostname: dozzle
    restart: *default-restart
    environment:
      - DOZZLE_REMOTE_HOST=tcp://hell:2375|HELL,tcp://inferno:2375|Inferno
    ports:
      - 8090:8080
    logging: *default-logging
```

**Comment by amir20** [comment]
Thanks. Will test it on my side.

**Comment by amir20** [comment]
So I tested this. I found possibly a different error. That's fixed now. Can you try `amir20/dozzle:master`. The error had nothing to do with remote hosts. 

Can you also go to `http://[yourdozzlehost]/healthcheck`? Does that look ok? Or is it an error?

**Comment by quorn23** [comment]
Pulled and switched to :master

healthcheck: `OK API Version 1.43`
hitting that endpoint, but within Dozzle it still shows the Dozzle container as unhealthy.

**Comment by amir20** [comment]
OK so the end point is healthy. Something might be wrong on the client. Let me try to add some debugging logs.

**Comment by amir20** [comment]
Ok try `amir20/dozzle:pr-2513` which adds logging at #2513. 

Then you should be able to do `docker exec  [dozzle_container_id]  /dozzle healthcheck`, 

You should see something like 

```
level=info msg="Checking health of http://localhost:8080//healthcheck"
level=info msg="Healthcheck passed"
```

If you see an error, that would be your problem.  If you don't see an error, and it is still unhealthy then I am not sure what is happening.

**Comment by quorn23** [comment]
```
docker exec dozzle /dozzle healthcheck
level=info msg="Checking health of http://localhost:8080//healthcheck"
level=info msg="Healthcheck passed"
```

```
docker ps | grep dozzle
1c693ce9f158   amir20/dozzle:pr-2513                        "/dozzle"                2 minutes ago   Up 2 minutes (unhealthy)   0.0.0.0:8090->8080/tcp, :::8090->8080/tcp
```

Sadly still unhealthy

**Comment by amir20** [comment]
Can you check your compose file with the healthcheck command? I'll try it locally and see if it I can reproduce.

**Comment by amir20** [comment]
Hmm

```
version: "3"
services:
  dozzle:
    image: amir20/dozzle:latest
    ports:
      - 8080:8080
    environment:
      - DOZZLE_REMOTE_HOST=tcp://64.225.88.189:2376
    volumes:
      - /path/to/certs:/certs  
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
```

```
❯ docker ps
CONTAINER ID   IMAGE                  COMMAND     CREATED          STATUS                    PORTS                                       NAMES
5766931776fb   amir20/dozzle:latest   "/dozzle"   30 seconds ago   Up 29 seconds (healthy)   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   test-dozzle-1
```

So it seems it is working for me. I used `master`. 

I think something else is happening so hopefully you can debug tomorrow.

**Comment by quorn23** [comment]
Adding the health check manually to compose seems to work fine. Container shows up healthy. 
But i'm a bit at a loss here, as now removing the health check in compose, dozzle doesn't show the health check itself.

with master i never get healthcheck passed:
```
docker exec dozzle /dozzle healthcheck
level=info msg="Checking health of http://localhost:8080//healthcheck"
```

```
docker ps | grep dozzle
fc7cb019fbaf   amir20/dozzle:master                         "/dozzle"                3 minutes ago   Up 3 minutes           0.0.0.0:8090->8080/tcp, :::8090->8080/tcp                                                                  dozzle
```

With pr-2513 i do, but it never reports the container as healthy

```
level=info msg="Checking health of http://localhost:8080//healthcheck"
level=info msg="Healthcheck passed"
```

```
docker ps | grep dozzle
89f768949d08   amir20/dozzle:pr-2513                        "/dozzle"                2 minutes ago   Up 2 minutes           0.0.0.0:8090->8080/tcp, :::8090->8080/tcp                                                                  dozzle
```

**Comment by amir20** [comment]
Hi @quorn23, I am confused a little. Dozzle by default doesn't enable healthcheck. You have to enable it manually in your compose file. 

> Adding the health check manually to compose seems to work fine. Container shows up healthy.

So this is expected. It is documented at https://dozzle.dev/guide/healthcheck. What you are describing is expected behavior. 

Was this bug expecting healthcheck to be enabled without manually enabling it? Looking at it, I am not sure.

**Comment by quorn23** [comment]
> Hi @quorn23, I am confused a little. Dozzle by default doesn't enable healthcheck. You have to enable it manually in your compose file.
> Was this bug expecting healthcheck to be enabled without manually enabling it? Looking at it, I am not sure.

It leaves me confused as well, maybe some odd docker caching bug, as it seems to be working with :master i'm happy with closing this FR and just keeping an eye out on releases and switch back to latest once it hits, as master works with the definied health check and no errors in the log anymore. I don't think it's worth chasing a ghost, when it seems to be working as intended like this.

**Comment by amir20** [comment]
Sounds good. I'll test a little more and release when I get a chance.

**Comment by amir20** [comment]
Released master last night. Let me know if something is broken.

**Comment by quorn23** [comment]
Looks good at first glance, i'll inform you if i would find anything off.
