### ISSUE TITLE
User icon shows the "unavailable image link" icon

### ISSUE THREAD

**Issue by truppelito** [amir20/dozzle#2591]
**Describe the bug**
The following is shown:
<img width="136" alt="Screenshot 2023-12-13 at 09 19 24" src="https://github.com/amir20/dozzle/assets/1059798/47afe5c6-7331-41d3-9a23-008ce7a406ee">
I suppose this is not intended behaviour.

**To Reproduce**
I have the following docker compose config:
```
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    environment:
      - DOZZLE_AUTH_PROVIDER=simple
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dozzle/data:/data
    ports:
      - 52043:8080
```

And the following in dozzle/data/users.yml
```
users:
  # "admin" here is username
  admin:
    name: "Admin"
    # Just sha-256 which can be computed with "echo -n password | shasum -a 256"
    password: "..."
```

I have tested with adding an email to the "admin:", but also got the same icon.

**Desktop (please complete the following information):**

- OS: RaspberryPi OS
- Docker version:
```
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:15 2023
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:15 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.26
  GitCommit:        3dd1e886e55dd695541fdcd67420c2888645a495
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Browser & version: Chrome, latest
- Version: Dozzle 5.7.0

**Comment by amir20** [comment]
I wasn't able to reproduce this.  I see

<img width="189" alt="Screenshot 2023-12-13 at 8 13 41 AM" src="https://github.com/amir20/dozzle/assets/260667/9b9c60fa-739c-4f6d-8c36-790867fd275b">


I use https://ui-avatars.com/ to generate fallback profile icons when gravatar profile icons don't exist.  So possibly few things could be the problem: 

1. Gravatar or ui-avatars were offline and it broke
2. Images for some reason were blocked 
3. Browser is blocking it, I also use Chrome so doubt it's this one 

If the problem hasn't gone away then right click on the icon and tell me the src of the `<img/>`. That way we can figure out if it is related to something Dozzle is doing.

**Comment by truppelito** [comment]
This is what I see:
<img width="1036" alt="Screenshot 2023-12-14 at 13 33 20" src="https://github.com/amir20/dozzle/assets/1059798/1aa38955-30e6-43dd-bf0c-0c3c46d70872">
It seems the `img` tag just doesn't have a `src` attribute?

**Comment by truppelito** [comment]
I can confirm that, even if I add an email and restart Dozzle, the same still happens. `users.yml`:
```
users:
  # "admin" here is username
  admin:
    name: "Admin"
    # Just sha-256 which can be computed with "echo -n password | shasum -a 256"
    password: "..."
    email: test@test.local

```

**Comment by amir20** [comment]
Looking at the [code](https://github.com/amir20/dozzle/blob/937638dce5346c82211e23def2b277cc742727c2/internal/auth/users.go#L24-L26), I can see how no email would be result in a missing avatar. 

However, using your [example](https://github.com/amir20/dozzle/issues/2591#issuecomment-1856135286) above. With email, `test@test.local`, I do see an icon. 

<img width="109" alt="Screenshot 2023-12-14 at 9 53 23 AM" src="https://github.com/amir20/dozzle/assets/260667/bb4c8e34-5990-475b-8392-d6ef0794c6e9">

Can you investigate why that is breaking for you?  Can you look at the `src` again? 

I also want to make it so that Dozzle doesn't need to be restarted if `users.yml` changes. 

Thanks!

**Comment by amir20** [comment]
See #2593 and #2594. Should be merged in master now. Can you try `amir20/dozzle:master`? 

I still don't know why with email you see a missing image. So waiting to hear how that is possible.

**Comment by amir20** [comment]
Marking as fixed because without email should work now.

**Comment by jicho** [comment]
Hi,

I'm still getting 
![image](https://github.com/amir20/dozzle/assets/610740/5a6deb68-5760-41a0-bc9c-a556d7ca53de)
 in Safari and my other browsers.

I'm running version 5.7.1, when I'm correct this issue should be solved.
Oh... and in users.yml I have no email address.

And for some more info... This is generated in the HTML:
![image](https://github.com/amir20/dozzle/assets/610740/af82cd0d-f806-4ebf-ad65-9785280281bb)

This is visible in de browser console:
![image](https://github.com/amir20/dozzle/assets/610740/50b75aed-8810-42b6-ab05-df0feb55021c)

And when I directly go to https://gravatar.com/avatar/0ea101bffba985a8ff23f3d2dd1b590d?d=https%3A%2F%2Fui-avatars.com%2Fapi%2F/Eric/128 I'm begin redirected to https://i2.wp.com/ui-avatars.com/api//Eric/128?ssl=1

With an this icon as a result:
<img width="125" alt="image" src="https://github.com/amir20/dozzle/assets/610740/4a4a2548-c5f2-48b5-834a-defafd6bb8e6">

So my add blocker isn't causing the issue :)

Any ideas?

P.S.: Keep up the nice work with Dozzle! Great tool and easy to use 👏

**Comment by amir20** [comment]
Hmmmm..... I see this now. I haven't tested it but the redirect happens to me too. Which is frustrating because I don't expect an image to redirect. 

I'll have to see if I can see a fix on my side. I'll reopen.

**Comment by EDIflyer** [comment]
Just to confirm I'm seeing this issue on one site too (it's one where I have a login email but it isn't linked to a Gravatar ID.

If I follow the URL directly id just redirects me to https://i2.wp.com/ui-avatars.com/api///128?ssl=1 with '12' in it!
![image](https://github.com/amir20/dozzle/assets/13610277/30cc7b1a-3cb4-42b2-8675-48e582cfdffc)

**Comment by amir20** [comment]
Yea, I was able to finally reproduce this. Something recently must have changed. I think I can try to fix it later.

**Comment by amir20** [comment]
Can you all try `amir20/dozzle:pr-2599`? It should work but I am not sure if I am supposed whitelist any other domains besides `i2.wp.com`.

**Comment by amir20** [comment]
I think I found a good fix.

**Comment by amir20** [comment]
So closing.

**Comment by EDIflyer** [comment]
It's not a broken image anymore but I get a '12' for some reason?  Not sure why that is of if we can just leave blank if no Gravatar available?

![image](https://github.com/amir20/dozzle/assets/13610277/23f43d67-d2fa-4a3e-a758-530aa88fda72)

**Comment by amir20** [comment]
> Not sure why that is of if we can just leave blank if no Gravatar available?

The problem is I do not if it is blank. Gravatar doesn't tell the client it is blank. 

> Have updated to the latest release and it's not a broken image anymore but I get a '12' for some reason?

That is weird for sure. I can take a guess. Can you let me know what `Name:` you are using? Paste your `users.yml` without password so I can test it? You can email it to me too. 

Thanks @EDIflyer !

**Comment by EDIflyer** [comment]
Have pinged you an email!

**Comment by jicho** [comment]
Just installed the latest release, looks like the problem is fixed at this end:

![image](https://github.com/amir20/dozzle/assets/610740/78f1266a-058e-4e4a-8080-e79e67031e4b)

The console errors are also gone (as expected now that the icon is visible).

Thanks!

**Comment by truppelito** [comment]
It's currently working for me too!

**Comment by EDIflyer** [comment]
> > Have updated to the latest release and it's not a broken image anymore but I get a '12' for some reason?
> 
> That is weird for sure. I can take a guess. Can you let me know what `Name:` you are using? Paste your `users.yml` without password so I can test it? You can email it to me too.

PS further to my email found from another bug that it was `/data` that I had to map to access config files. Have done so and after it initially being empty I changed a setting about found a `profile.json` in `data/EDIflyer` however no `users.yml`.  I'm not using user management though, just `--forward-proxy` - not sure if that's related?  It works find for the sites where the Authelia user has an email addresses known to Gravatar but not for this one (which isn't a known email).  No longer a broken image but this weird '12'!

**Comment by amir20** [comment]
@EDIflyer I think you have a different issue. Got your email. Haven't tried it yet. I had forgotten you are using proxy. So you wouldn't see a users file. 

I think something is happening with the name when generating avatar. So I'll test it and see if I can reproduce.
